#! /bin/bash
#
# Docker wrapper script for common commands.

CONFIG_FILENAME="config"
NAME="${NAME:=jasonish/centos-suricata}"
TAG="${TAG:=stable}"
IMAGE="${NAME}:${TAG}"

if [ -e ${CONFIG_FILENAME} ]; then
    . ${CONFIG_FILENAME}
    DOCKER_ENV_FILE=${CONFIG_FILENAME}
fi

build() {
    docker build ${BUILD_OPTS} --rm -t ${IMAGE} image
}

run() {
    tty > /dev/null && tty="--tty=true" || tty="--tty=false"
    test -e "${CONFIG_FILENAME}" && env_file="--env-file=${CONFIG_FILENAME}"
    net="--net=${DOCKER_NET:=host}"
    volumes="-v $(pwd)/data:/data ${VOLUMES}"
    cidfile="--cidfile=${DOCKER_CIDFILE:=}"
    rm="--rm=${DOCKER_RM:=true}"
    entrypoint="--entrypoint=${DOCKER_ENTRYPOINT:=/tools/boot}"
    exec docker run -i \
	 ${tty} \
	 ${cidfile} \
	 ${rm} \
	 ${entrypoint} \
	 ${net} \
	 ${env_file} \
	 ${volumes} \
	 ${IMAGE} "$@"
}

SUPERVISOR_CIDFILE="supervisor.cid"

supervisor() {
    if [ -e "${SUPERVISOR_CIDFILE}" ]; then
	if ! docker inspect $(cat ${SUPERVISOR_CIDFILE}) > /dev/null 2>&1; then
	    rm -f "${SUPERVISOR_CIDFILE}"
	fi
    fi
    DOCKER_CIDFILE=${SUPERVISOR_CIDFILE}
    run /usr/bin/supervisord --nodaemon -c /etc/supervisord.conf
}

# Test if this Docker container is currently running in supervisor
# mode or not.
running_supervisor() {
    if [ -e "${SUPERVISOR_CIDFILE}" ]; then
	if docker inspect $(cat ${SUPERVISOR_CIDFILE}) > /dev/null 2>&1; then
	    return 0
	fi
    fi
    return 1
}

update() {
    update_cidfile=".update-cid"
    rm -f ${update_cidfile}
    (DOCKER_CIDFILE="${update_cidfile}" \
	    DOCKER_RM=false \
	    DOCKER_ENTRYPOINT="/tools/boot" \
	    run /tools/update) && \
	echo "Committing." && \
	docker commit $(cat ${update_cidfile}) ${IMAGE}
    rm -f ${update_cidfile}
}

update_rules() {
    if running_supervisor; then
	echo "Found Suricata running in supervisor mode."
	docker exec $(cat ${SUPERVISOR_CIDFILE}) idstools-rulecat
	echo "Restarting Suricata."
	docker exec $(cat ${SUPERVISOR_CIDFILE}) supervisorctl restart suricata
    else
	run idstools-rulecat
    fi
}

usage() {
cat <<EOF
usage: $0 <command> [args...]

commands:

    run [command]        - Default to a shell.
    build                - (Re)builds the container.
    update               - Update OS, Suricata, etc.
    update-rules         - Update Suricata rules.
    supervisor           - Run Suricata under supervisor.
 
EOF
}

case "$1" in

    build)
	build
	;;

    run)
	shift
	run "$@"
	;;

    update)
	update
	;;

    update-rules)
	update_rules
	;;

    supervisor)
	supervisor
	;;

    *)
	usage
	;;

esac
