#! /bin/sh
#
# Entry point script to make sure the container is setup for proper
# operation.

. /config

if [ ! -d /data ]; then
    echo "error: /data is not mounted as a volume"
    exit 1
fi

mkdir -p /data/etc/suricata
touch /data/etc/suricata/threshold.config
mkdir -p /data/var/log/suricata
mkdir -p /data/var/tmp/suricata

if [ ! -e /data/etc/suricata/rules ]; then
    cp -a /etc/suricata/rules /data/etc/suricata/rules
fi

(cd /data/etc/suricata && \
	RULECAT_LOG_LEVEL=WARNING idstools-rulecat --dump-sample-configs)

if [ ! "$1" ]; then
    exec /bin/bash
fi

exec "$@"
